### ISSUE TITLE
display user profile picture

### ISSUE THREAD

**Issue by bo-bok** [ConchobarMacNessa/mmedium-OAuth#26]
Currently: 

The correct image url logs to the terminal (along with the user's username).
However, whilst the username correctly displays, the avatar does not (instead it displays the alt text).

**Comment by finnhodgkin** [comment]
This is happening because on [these lines](https://github.com/ConchobarMacNessa/mmedium-OAuth/blob/master/src/views/partials/navbar.hbs#L51-L57) you're setting the values to 'username' and 'avatar_url' rather than 'credentials.username' and 'credentials.avatar_url'

The below code displays the avatar correctly:

```
{{#if credentials.username}}
    <div class='user_credentials'>
      <img class="item__avatar" src="{{credentials.avatar_url}}" alt="user avatar"/>
      <p class='welcome_note'>Welcome, {{credentials.username}} </p>
    </div>
    {{/if}}
```

**Comment by bo-bok** [comment]
merci :)
